name: medley-radio
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  radio:
    image: ghcr.io/seamless-medley/medley:latest
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - 3001:3001
      - 9989:9989
    environment:
      LOG_PRETTY: hide-date,use-colors
      FORCE_COLOR: 3
    volumes:
      - /Music-Station/medley/config.yml:/app/config.yml
      - /Music-Station/musics:/data/musics
      - /Music-Station/medley-drops:/data/medley-drops
